name: sample_app_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
